<script>
  import images from "../config/images.json";
  </script>

<h1 class="content text-lg md:text-xl text-left">👨🏽‍🎓 Hello fellow PieDAO students!</h1>

  
  <div class="content">
    <div class="justify-start items-start flex-col text-left">
      <h2 class="text-lg">Learn about PieDAO</h2>
      <p class="font-thin">If you are looking for the definitive PieDAO 101, look no more.</p>
    </div>
  </div>
  
  <div class="100pc max-w-1200px flex flex-wrap">

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://www.piedao.org/#/dough`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://raw.githubusercontent.com/pie-dao/brand/master/misc/metavote2.png) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">DOUGH</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">Learn about DOUGH</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">DOUGH is the building block of the DAO. Owning DOUGH makes you a part of the organisation, giving voting rights in all decisions. It’s not just about governance, DOUGH holders are also entitled to a revenue stream from fees generated by the protocol.</div>
      </a>
    </div>

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://medium.com/piedao/inside-the-bakery-how-we-build-pies-e8932718beaf`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://miro.medium.com/max/1400/1*ydCeYEcSSUiYxfHI-_ivag.jpeg) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">PIEs</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">The methodology behind pies indices</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">Building pies is a community-driven process with discourse happening on both our community Discord and Forum. A market-cap weight-based methodology is employed, giving larger allocation to higher market cap assets in order to maximise scalability.</div>
      </a>
    </div>

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://medium.com/piedao/how-to-mint-pies-gas-free-with-oven-1d11e902fab8`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://miro.medium.com/max/1400/1*5mzKpLdFqzEVNR0TLNOWIw.png) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">Oven</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">What is the Oven and How to Mint Pies Gas-Free.</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        The community Oven allows our users to get hold of pies gas-free by pooling their ETH and sharing the costs.
      </a>
    </div>

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://www.piedao.org/#/stake`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://raw.githubusercontent.com/pie-dao/brand/master/misc/amazingrewards4.png) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">Farming</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">PieDAO Farming opportunities</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        We’re incentivizing liquidity for our products with 150k of DOUGH available to earn each week and as much as 150% APR. Check out our farms to see the latest opportunities.      </a>
    </div>

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://medium.com/piedao/announcing-pievaults-19e2fa4c734e`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://miro.medium.com/max/1400/1*KABX967U0nJRoD3y5JLF4g.png) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">Vaults</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">What are PieVaults?</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        PieVaults are the DAO’s latest product range, unlocking active yield-generating strategies for each underlying asset in the index. Lending, native staking, and meta-governance are all possible. Yearn Ecosystem Pie ( $YPIE) is the first PieVault, giving complete exposure to the Yearn Finance ecosystem.      </a>
    </div>


  </div>



  <div class="content">
    <div class="justify-start items-start flex-col text-left  mt-8">
      <h2 class="text-lg">Learn about Pies</h2>
      <p class="font-thin">Pies are portfolio allocations governed by a DAO</p>
    </div>
  </div>
  
  <div class="100pc max-w-1200px flex flex-wrap">

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://medium.com/piedao/announcing-balanced-crypto-pie-bcp-btc-eth-and-defi-7a2423c5d94e?source=collection_home---6------7-----------------------`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://miro.medium.com/max/1400/0*bzsou8y11D4bhnaH) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">BCP</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">Learn about BCP</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        The most risk-minimised cryptocurrency portfolio, Balanced Crypto Pie is all you need. BCP gives equal Bitcoin, Ether, and DeFi exposure in one easy to access ERC20 token. The underlying assets in BCP are constantly taking profits and growing your holdings as it automatically rebalances to maintain the set allocation.      </a>
    </div>

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://medium.com/piedao/announcing-ypie-pievault-and-sushiswap-collaboration-a89b102e81e7`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://miro.medium.com/max/1400/1*FCMyDdToTcNI4hyq-lFE2g.png) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">YPIE</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">Learn about YPIE</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        Yearn Ecosystem PieVault: DeFi’s First Index With Native Staking and Lending.
      </a>
    </div>

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://medium.com/piedao/announcing-defi-and-a-comparative-index-performance-analysis-9f63e251120d`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://miro.medium.com/max/1400/0*fUHAQEzhGg_o0uYI.png) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">DEFI++</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">Learn about DEFI++</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        DEFI++ is the product for people looking for diversified exposure to DeFi assets. It includes both DeFi blue chips and small cap coins.
      </a>
    </div>

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://docs.piedao.org/current-pies/defi+l`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://raw.githubusercontent.com/pie-dao/brand/8c7134faa86baafd1e65aad95c51dac3f4b650f8/PIE%20Tokens/DeFi%2B%2BL.svg) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">DEFI+L</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">Learn about DEFI+L</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        Blue chips only. DEFI+L represents DeFi’s biggest and best. Like all our pies DEFI+L actively rebalances, constantly locking in profits as market prices fluctuate.      </a>
    </div>

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://medium.com/piedao/announcing-defi-s-67ed53367364`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://miro.medium.com/max/1400/1*m6QRyhTSsF-C99QF2VSAAg.png) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">DEFI+S</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">Learn about DEFI+S</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        Don’t sleep on the underdog. DEFI+S gives exposure to lower marketcap projects that have incredible potential for future growth.
      </a>
    </div>
    
  </div>


  <div class="content">
    <div class="justify-start items-start flex-col text-left  mt-8">
      <h2 class="text-lg">Miscellaneous</h2>
      <p class="font-thin">DeFi is growing fast, better keepinb up to date</p>
    </div>
  </div>
  
  <div class="100pc max-w-1200px flex flex-wrap">

    <div class="flex flex-col w-100pc thinborder hover:border-pink md:w-31pc h-420px bg-white rounded my-2 mx-2 md:my-1pc md:mx-1pc">
      <a class="" target="_blank" href={`https://docs.piedao.org/`}>
      <div class="w-100pc min-w-100pc h-200px flex items-start justify-end mb-4 rounded" style="background: url(https://gblobscdn.gitbook.com/assets%2F-M156s4roA8TRygFfSW8%2F-M1B59WcVd6oNyBAt8S1%2F-M1BE5jwQsMnghWTZEtB%2FScreenshot%20from%202020-02-28%2016-37-59.png?alt=media&token=60169b8e-9f2a-4c52-9b0e-94bd4312ef49) no-repeat center center; background-size: cover!important;">
        <div class="text-right mt-4 mr-4"><span class="text-xs font-bold text-white bg-black roundedxs px-2 py-1">DOCS</span></div>
      </div>
      <div class="text-left font-bold text-lg px-6 leading-7 mb-4">Documentation</div>
      <div class="text-justify font-thin h-120px text-ellipsis overflow-hidden px-6 leading-6 mb-4">
        Comunity managed PieDAO docs. This is a live document that will be updated as PieDAO evolves. We aim to provide a detailed view of the various goals, software, and products provided through PieDAO.      </a>
    </div>
    
  </div>
  
  