<div class="content">
  <div class="flex flex-col flex-start">
    <h2
      class="text-xl text-center mt-0 mb-2 leading-tight font-heading md:text-left md:mt-2 md:mb-6">
      Learn more about PieDAO
    </h2>

    <a
      class="learn-link fit-content text-left text-lg"
      target="_blank"
      href="https://medium.com/piedao/inside-the-bakery-how-we-build-pies-e8932718beaf">What is the methodology behind pies indices?
    </a>
    <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px mt-1 ml-5px">
      Building pies is a community-driven process with discourse happening on both our community Discord and Forum. A market-cap weight-based methodology is employed, giving larger allocation to higher market cap assets in order to maximise scalability.
    </p>

    <a
      class="learn-link fit-content text-left text-lg"
      target="_blank"
      href="https://medium.com/piedao/how-to-mint-pies-gas-free-with-oven-1d11e902fab8">
      What is the Oven and How to Mint Pies Gas-Free.
    </a>
    <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
      The community Oven allows our users to get hold of pies gas-free by pooling their ETH and sharing the costs.    </p>

    <a
      class="learn-link fit-content text-left text-lg"
      target="_blank"
      href="#/stake">
      PieDAO Farming opportunities
    </a>
    <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
      We’re incentivizing liquidity for our products with 150k of DOUGH available to earn each week and as much as 150% APR. Check out our farms to see the latest opportunities.    </p>

    <a
      class="learn-link fit-content text-left text-lg"
      target="_blank"
      href="https://medium.com/piedao/announcing-pievaults-19e2fa4c734e">What are PieVaults?
    </a>
    <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
      PieVaults are the DAO’s latest product range, unlocking active yield-generating strategies for each underlying asset in the index. Lending, native staking, and meta-governance are all possible. Yearn Ecosystem Pie ( $YPIE) is the first PieVault, giving complete exposure to the Yearn Finance ecosystem.
    </p>

  <a
    class="learn-link fit-content text-left text-lg"
    href="#/dough">Learn about DOUGH
  </a>
  <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
    DOUGH is the building block of the DAO. Owning DOUGH makes you a part of the organisation, giving voting rights in all decisions. It’s not just about governance, DOUGH holders are also entitled to a revenue stream from fees generated by the protocol.
  </p>

  <h2
      class="text-xl text-center mt-0 mb-2 leading-tight font-heading md:text-left md:mt-2 md:mb-6">
      Learn more about Pies
  </h2>

  <a
    class="learn-link fit-content text-left text-lg"
    target="_blank"
    href="https://medium.com/piedao/announcing-balanced-crypto-pie-bcp-btc-eth-and-defi-7a2423c5d94e?source=collection_home---6------7-----------------------">Learn about BCP
  </a>
  <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
    The most risk-minimised cryptocurrency portfolio, Balanced Crypto Pie is all you need. BCP gives equal Bitcoin, Ether, and DeFi exposure in one easy to access ERC20 token. The underlying assets in BCP are constantly taking profits and growing your holdings as it automatically rebalances to maintain the set allocation.
  </p>

  <a
    class="learn-link fit-content text-left text-lg"
    target="_blank"
    href="https://medium.com/piedao/announcing-ypie-pievault-and-sushiswap-collaboration-a89b102e81e7">Learn about YPIE
  </a>
  <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
    Yearn Ecosystem PieVault: DeFi’s First Index With Native Staking and Lending.
  </p>

  <a
    class="learn-link fit-content text-left text-lg"
    target="_blank"
    href="https://medium.com/piedao/announcing-defi-and-a-comparative-index-performance-analysis-9f63e251120d">Learn about DEFI++
  </a>
  <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
    DEFI++ is the product for people looking for diversified exposure to DeFi assets. It includes both DeFi blue chips and small cap coins.
  </p>

  <a
    class="learn-link fit-content text-left text-lg"
    target="_blank"
    href="https://docs.piedao.org/current-pies/defi+l">Learn about DEFI+L
  </a>
  <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
    Blue chips only. DEFI+L represents DeFi’s biggest and best. Like all our pies DEFI+L actively rebalances, constantly locking in profits as market prices fluctuate.
  </p>

  <a
    class="learn-link fit-content text-left text-lg"
    target="_blank"
    href="https://medium.com/piedao/announcing-defi-s-67ed53367364">Learn about DEFI+S
  </a>
  <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
    Don’t sleep on the underdog. DEFI+S gives exposure to lower marketcap projects that have incredible potential for future growth. 
  </p>

  <h2
      class="text-xl text-center mt-0 mb-2 leading-tight font-heading md:text-left md:mt-2 md:mb-6">
      Miscellaneous
  </h2>

  <a
    class="learn-link fit-content text-left text-lg"
    target="_blank"
    href="https://docs.piedao.org/">Documentation
  </a>
  <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
    Comunity managed PieDAO docs. This is a live document that will be updated as PieDAO evolves. We aim to provide a detailed view of the various goals, software, and products provided through PieDAO.
  </p>


  </div>
</div>
