<div class="content">
  <div class="flex flex-col flex-start">
    <h2
      class="text-xl text-center mt-0 mb-2 leading-tight font-heading md:text-left md:mt-2 md:mb-6">
      Learn more about PieDAO and Pies
    </h2>

    <a
      class="learn-link fit-content text-left text-lg"
      target="_blank"
      href="https://medium.com/piedao/inside-the-bakery-how-we-build-pies-e8932718beaf">Inside the
      Bakery: How We Build Pies
    </a>
    <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px mt-1 ml-5px">
      Building pies is a community-driven process with discourse happening on both our community Discord and Forum. A market-cap weight-based methodology is employed, giving larger allocation to higher market cap assets in order to maximise scalability.
    </p>

    <a
      class="learn-link fit-content text-left text-lg"
      target="_blank"
      href="https://medium.com/piedao/how-to-mint-pies-gas-free-with-oven-1d11e902fab8">
      How to Mint Pies Gas-Free With Oven
    </a>
    <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
      The community Oven allows our users to get hold of pies gas-free by pooling their ETH and sharing the costs.    </p>

    <a
      class="learn-link fit-content text-left text-lg"
      target="_blank"
      href="https://pools.piedao.org/#/stake">
    How to maximise yield with PieDAO Farming opportunities
    </a>
    <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
      We’re incentivizing liquidity for our products with 150k of DOUGH available to earn each week and as much as 150% APR. Check out our farms to see the latest opportunities.    </p>

    <a
      class="learn-link fit-content text-left text-lg"
      target="_blank"
      href="https://medium.com/piedao/announcing-pievaults-19e2fa4c734e">Pie Valults
    </a>
    <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
      PieVaults are the DAO’s latest product range, unlocking active yield-generating strategies for each underlying asset in the index. Lending, native staking, and meta-governance are all possible. Yearn Ecosystem Pie ( $YPIE) is the first PieVault, giving complete exposure to the Yearn Finance ecosystem.
    </p>

    <a
    class="learn-link fit-content text-left text-lg"
    target="_blank"
    href="https://pools.piedao.org/#/dough">Learn about DOUGH
  </a>
  <p class="learn-description font-thin text-base mb-8 mt-1 ml-5px">
    DOUGH is the building block of the DAO. Owning DOUGH makes you a part of the organisation, giving voting rights in all decisions. It’s not just about governance, DOUGH holders are also entitled to a revenue stream from fees generated by the protocol.

  </p>


  </div>
</div>
